package AdditionApp;


/**
* AdditionApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Tuesday, 28 September, 2021 5:39:31 PM IST
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
